# Generated by Django 5.1.6 on 2025-09-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_rename_group_student_student_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="student_gender",
            field=models.CharField(default="N/A", max_length=1),
        ),
        migrations.AddField(
            model_name="student",
            name="student_height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Peso (g)",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Altura (cm)",
            ),
        ),
    ]
