# Generated by Django 5.1.6 on 2025-09-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_student_age_student_student_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_height",
            field=models.FloatField(default=None, verbose_name="Peso (g)"),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_weight",
            field=models.FloatField(default=None, verbose_name="Altura (cm)"),
        ),
    ]
