# Generated by Django 5.1.6 on 2025-09-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_student_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_diet_restriction",
            field=models.TextField(default=None),
        ),
    ]
