# Generated by Django 5.1.6 on 2025-09-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_student_student_diet_restriction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_diet_restriction",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
