# Generated by Django 5.1.6 on 2025-09-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_student_student_diet_restriction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_height",
            field=models.FloatField(default=None, verbose_name="Altura (cm)"),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_weight",
            field=models.IntegerField(default=0, max_length=5, verbose_name="Peso (g)"),
        ),
    ]
