# Generated by Django 5.1.6 on 2025-09-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_alter_student_student_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_weight",
            field=models.IntegerField(default=0, verbose_name="Peso (g)"),
        ),
    ]
