# Generated by Django 5.1.6 on 2025-04-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibgefood',
            name='acido_linoleico_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ácido linoleico (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='acido_linolenico_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ácido linolênico (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='acucar_adicionado_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Açúcares adicionados (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='acucar_total_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Açúcares totais (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='ag_monoinsaturados_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ácidos graxos monoinsaturados (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='ag_poliinsaturados_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ácidos graxos poliinsaturados (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='ag_saturados_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ácidos graxos saturados (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='ag_trans_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ácidos graxos trans (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='calcio_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cálcio (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='carboidrato_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Carboidratos (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='cobalamina_mcg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cobalamina (B12) (µg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='cobre_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cobre (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='codigo_de_preparacao',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='colesterol_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Colesterol (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='energia_kcal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Energia (kcal)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='ferro_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ferro (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='fibra_alimentar_total_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fibras alimentares (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='folato_dfe_mcg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Folato (DFE µg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='fosforo_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fósforo (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='lipidios_totais_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lipídios totais (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='magnesio_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Magnésio (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='manganes_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Manganês (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='niacina_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Niacina (B3) (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='niacina_ne_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Equivalentes de niacina (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='piridoxina_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Piridoxina (B6) (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='potassio_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Potássio (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='proteina_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Proteínas (g)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='retinol_mcg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retinol (µg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='riboflavina_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Riboflavina (B2) (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='selenio_mcg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Selênio (µg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='sodio_adicionado_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sódio adicionado (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='sodio_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sódio (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='tiamina_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tiamina (B1) (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='vitamina_a_rae_mcg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vitamina A (RAE µg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='vitamina_c_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vitamina C (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='vitamina_d_mcg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vitamina D (µg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='vitamina_e_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vitamina E (mg)'),
        ),
        migrations.AlterField(
            model_name='ibgefood',
            name='zinco_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zinco (mg)'),
        ),
    ]
