# Generated by Django 5.1.6 on 2025-04-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IBGEFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('descricao_do_alimento', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=80)),
                ('codigo_de_preparacao', models.CharField(max_length=3)),
                ('descricao_da_preparacao', models.CharField(max_length=80)),
                ('energia_kcal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proteina_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lipidios_totais_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carboidrato_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fibra_alimentar_total_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colesterol_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ag_saturados_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ag_monoinsaturados_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ag_poliinsaturados_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acido_linoleico_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acido_linolenico_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ag_trans_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acucar_total_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acucar_adicionado_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calcio_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('magnesio_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manganes_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fosforo_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ferro_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sodio_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sodio_adicionado_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potassio_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobre_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zinco_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selenio_mcg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retinol_mcg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamina_a_rae_mcg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiamina_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('riboflavina_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('niacina_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('niacina_ne_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piridoxina_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cobalamina_mcg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('folato_dfe_mcg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamina_d_mcg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamina_e_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamina_c_mg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alimento IBGE',
                'verbose_name_plural': 'Alimentos IBGE',
                'ordering': ['descricao_do_alimento'],
            },
        ),
    ]
